### ISSUE TITLE
Possible Bug: capability.h Unknown Types

### ISSUE THREAD

**Issue by mahuika88** [hugsy/sstoper#1]
This may be a totally stupid user error on my part but I've tried a lot and nothing seems to work. I'm running on Fedora 20 and getting this stack trace when running make. I believe I have installed all the necessary dependencies but could have missed one.

make
gcc -O2 -Wall -D PROGNAME=\"SSToPer\" -D VERSION=0.21 -I/usr/include  -L/usr/lib64 -c -o main.o main.c
In file included from main.c:48:0:
/usr/include/sys/capability.h:116:19: error: unknown type name ‘cap_user_header_t’
 extern int capset(cap_user_header_t header, cap_user_data_t data);
                   ^
/usr/include/sys/capability.h:116:45: error: unknown type name ‘cap_user_data_t’
 extern int capset(cap_user_header_t header, cap_user_data_t data);
                                             ^
/usr/include/sys/capability.h:117:19: error: unknown type name ‘cap_user_header_t’
 extern int capget(cap_user_header_t header, const cap_user_data_t data);
                   ^
/usr/include/sys/capability.h:117:19: error: unknown type name ‘cap_user_data_t’
main.c: In function ‘main’:
main.c:866:24: error: ‘CAP_KILL’ undeclared (first use in this function)
       retcode = is_cap(CAP_KILL);
                        ^
main.c:866:24: note: each undeclared identifier is reported only once for each function it appears in
main.c:872:24: error: ‘CAP_SETUID’ undeclared (first use in this function)
       retcode = is_cap(CAP_SETUID);
                        ^
make: **\* [main.o] Error 1

**Comment by hugsy** [comment]
Have you installed all dependencies ?

``` bash
yum install openssl-devel gnutls-devel libcap-devel
```

**Comment by mahuika88** [comment]
It looks like I was missing openssl-devel. That got rid of the last few
errors but I'm still getting this doing a make:

make
gcc -O2 -Wall -D PROGNAME=\"SSToPer\" -D VERSION=0.21 -I/usr/include
 -L/usr/lib64 -c -o main.o main.c
In file included from main.c:48:0:
/usr/include/sys/capability.h:116:19: error: unknown type name
‘cap_user_header_t’
 extern int capset(cap_user_header_t header, cap_user_data_t data);
                   ^
/usr/include/sys/capability.h:116:45: error: unknown type name
‘cap_user_data_t’
 extern int capset(cap_user_header_t header, cap_user_data_t data);
                                             ^
/usr/include/sys/capability.h:117:19: error: unknown type name
‘cap_user_header_t’
 extern int capget(cap_user_header_t header, const cap_user_data_t data);
                   ^
/usr/include/sys/capability.h:117:19: error: unknown type name
‘cap_user_data_t’
main.c: In function ‘main’:
main.c:866:24: error: ‘CAP_KILL’ undeclared (first use in this function)
       retcode = is_cap(CAP_KILL);
                        ^
main.c:866:24: note: each undeclared identifier is reported only once for
each function it appears in
main.c:872:24: error: ‘CAP_SETUID’ undeclared (first use in this function)
       retcode = is_cap(CAP_SETUID);

**Comment by hugsy** [comment]
Hi !

From the trace you sent me, it looks like the problem is coming from missing capabilities library on your system. I created a Fedora 20 VM here and I could compile without any problem. Did you try removing libcap-devel and re yum-install it again ?
